//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace StdEqpTesting.Localization {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Loc {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Loc() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StdEqpTesting.Localization.Loc", typeof(Loc).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Additional Info 的本地化字符串。
        /// </summary>
        public static string AddInfo {
            get {
                return ResourceManager.GetString("AddInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add -&gt; 的本地化字符串。
        /// </summary>
        public static string AddRecvStr {
            get {
                return ResourceManager.GetString("AddRecvStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add a Unit 的本地化字符串。
        /// </summary>
        public static string AddUnit {
            get {
                return ResourceManager.GetString("AddUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Addition Failed: Unit is empty or whitespace. 的本地化字符串。
        /// </summary>
        public static string AddUnitFail_Empty {
            get {
                return ResourceManager.GetString("AddUnitFail_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Addition Failed: Unit already exists. 的本地化字符串。
        /// </summary>
        public static string AddUnitFail_Existed {
            get {
                return ResourceManager.GetString("AddUnitFail_Existed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Addition Successful. 的本地化字符串。
        /// </summary>
        public static string AddUnitSucc {
            get {
                return ResourceManager.GetString("AddUnitSucc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save current unit to a file for future use. 的本地化字符串。
        /// </summary>
        public static string AddUnitTT {
            get {
                return ResourceManager.GetString("AddUnitTT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Auto add 的本地化字符串。
        /// </summary>
        public static string AutoAddRecvStr {
            get {
                return ResourceManager.GetString("AutoAddRecvStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 When serial port is opened, automatically add the received string to data list if no more data is received in 1 second. 的本地化字符串。
        /// </summary>
        public static string AutoAddRecvStrTT {
            get {
                return ResourceManager.GetString("AutoAddRecvStrTT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Average Value 的本地化字符串。
        /// </summary>
        public static string Average {
            get {
                return ResourceManager.GetString("Average", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The average value of numbers in Data List. 的本地化字符串。
        /// </summary>
        public static string AverageTT {
            get {
                return ResourceManager.GetString("AverageTT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Baud Rate 的本地化字符串。
        /// </summary>
        public static string BaudRate {
            get {
                return ResourceManager.GetString("BaudRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Auto clear 的本地化字符串。
        /// </summary>
        public static string ClearAfterAddingRecvStr {
            get {
                return ResourceManager.GetString("ClearAfterAddingRecvStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 When auto add is on, auto clear is enforced. 的本地化字符串。
        /// </summary>
        public static string ClearAfterAddingRecvStrDisabledTT {
            get {
                return ResourceManager.GetString("ClearAfterAddingRecvStrDisabledTT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Clear received string after it&apos;s been added to the data list. 的本地化字符串。
        /// </summary>
        public static string ClearAfterAddingRecvStrTT {
            get {
                return ResourceManager.GetString("ClearAfterAddingRecvStrTT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Close Port 的本地化字符串。
        /// </summary>
        public static string ClosePort {
            get {
                return ResourceManager.GetString("ClosePort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Serial Port %Name closed 的本地化字符串。
        /// </summary>
        public static string COMClose {
            get {
                return ResourceManager.GetString("COMClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Serial Port %Name opened 的本地化字符串。
        /// </summary>
        public static string COMOpen {
            get {
                return ResourceManager.GetString("COMOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Settings for %PortName has been saved 的本地化字符串。
        /// </summary>
        public static string COMSettingSaved {
            get {
                return ResourceManager.GetString("COMSettingSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Confirm Addition of Incomplete Record 的本地化字符串。
        /// </summary>
        public static string ConfirmAddEmptyRecord {
            get {
                return ResourceManager.GetString("ConfirmAddEmptyRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You&apos;re seeing this because Test Name or Unit is left empty or are of whitespaces.
        ///
        ///Press No to go back so you can make some changes, otherwise you can press Yes to add this incomplete record, which can cause confusion. 的本地化字符串。
        /// </summary>
        public static string ConfirmAddEmptyRecordDesc {
            get {
                return ResourceManager.GetString("ConfirmAddEmptyRecordDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Data Bits 的本地化字符串。
        /// </summary>
        public static string DataBits {
            get {
                return ResourceManager.GetString("DataBits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Connecting to database.... 的本地化字符串。
        /// </summary>
        public static string DBConnect {
            get {
                return ResourceManager.GetString("DBConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Encoding 的本地化字符串。
        /// </summary>
        public static string Encoding {
            get {
                return ResourceManager.GetString("Encoding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 %Num COM device(s) detected 的本地化字符串。
        /// </summary>
        public static string FoundCOMDevices {
            get {
                return ResourceManager.GetString("FoundCOMDevices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Handshake 的本地化字符串。
        /// </summary>
        public static string Handshake {
            get {
                return ResourceManager.GetString("Handshake", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Login 的本地化字符串。
        /// </summary>
        public static string LoginButton {
            get {
                return ResourceManager.GetString("LoginButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please enter your credentials below. 的本地化字符串。
        /// </summary>
        public static string LoginEnterCred {
            get {
                return ResourceManager.GetString("LoginEnterCred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Wrong username or password. 的本地化字符串。
        /// </summary>
        public static string LoginFailedStatus {
            get {
                return ResourceManager.GetString("LoginFailedStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Password: 的本地化字符串。
        /// </summary>
        public static string LoginPassword {
            get {
                return ResourceManager.GetString("LoginPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Password only contains ASCII characters.
        ///And should have at least 4 characters. 的本地化字符串。
        /// </summary>
        public static string LoginPWErrorTT {
            get {
                return ResourceManager.GetString("LoginPWErrorTT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Username only contains letters, numbers and underscores.
        ///And have no more than 20 characters. 的本地化字符串。
        /// </summary>
        public static string LoginUNErrorTT {
            get {
                return ResourceManager.GetString("LoginUNErrorTT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Username: 的本地化字符串。
        /// </summary>
        public static string LoginUsername {
            get {
                return ResourceManager.GetString("LoginUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Welcome! 的本地化字符串。
        /// </summary>
        public static string LoginWelcome {
            get {
                return ResourceManager.GetString("LoginWelcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Login 的本地化字符串。
        /// </summary>
        public static string LoginWndTitle {
            get {
                return ResourceManager.GetString("LoginWndTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Loading 的本地化字符串。
        /// </summary>
        public static string MainWndTitle {
            get {
                return ResourceManager.GetString("MainWndTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Export 的本地化字符串。
        /// </summary>
        public static string NavExport {
            get {
                return ResourceManager.GetString("NavExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Image Device 的本地化字符串。
        /// </summary>
        public static string NavImg {
            get {
                return ResourceManager.GetString("NavImg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Proximity Sensor 的本地化字符串。
        /// </summary>
        public static string NavProx {
            get {
                return ResourceManager.GetString("NavProx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Review 的本地化字符串。
        /// </summary>
        public static string NavReview {
            get {
                return ResourceManager.GetString("NavReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Settings 的本地化字符串。
        /// </summary>
        public static string NavSettings {
            get {
                return ResourceManager.GetString("NavSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Measure (COM) 的本地化字符串。
        /// </summary>
        public static string NavTest {
            get {
                return ResourceManager.GetString("NavTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No COM port detected 的本地化字符串。
        /// </summary>
        public static string NoCOMTabHeader {
            get {
                return ResourceManager.GetString("NoCOMTabHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please check your settings and press F5 to refresh. 的本地化字符串。
        /// </summary>
        public static string NoCOMTabInstruction {
            get {
                return ResourceManager.GetString("NoCOMTabInstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Value is not saved 的本地化字符串。
        /// </summary>
        public static string NotSaved2DB {
            get {
                return ResourceManager.GetString("NotSaved2DB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open Port 的本地化字符串。
        /// </summary>
        public static string OpenPort {
            get {
                return ResourceManager.GetString("OpenPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Parity 的本地化字符串。
        /// </summary>
        public static string Parity {
            get {
                return ResourceManager.GetString("Parity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Port Properties 的本地化字符串。
        /// </summary>
        public static string PortProp {
            get {
                return ResourceManager.GetString("PortProp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ^^^^Properties^^^^ 的本地化字符串。
        /// </summary>
        public static string PortPropExpander {
            get {
                return ResourceManager.GetString("PortPropExpander", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Read Timeout 的本地化字符串。
        /// </summary>
        public static string ReadT {
            get {
                return ResourceManager.GetString("ReadT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Recv. String 的本地化字符串。
        /// </summary>
        public static string RecvStr {
            get {
                return ResourceManager.GetString("RecvStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 🔄 Refresh 的本地化字符串。
        /// </summary>
        public static string RefreshBtn {
            get {
                return ResourceManager.GetString("RefreshBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Register 的本地化字符串。
        /// </summary>
        public static string RegisterButton {
            get {
                return ResourceManager.GetString("RegisterButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Confirm your password below: 的本地化字符串。
        /// </summary>
        public static string RegisterConfirmPass {
            get {
                return ResourceManager.GetString("RegisterConfirmPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You&apos;ll be registered as: 的本地化字符串。
        /// </summary>
        public static string RegisterConfirmUser {
            get {
                return ResourceManager.GetString("RegisterConfirmUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please always remember your username and password. 的本地化字符串。
        /// </summary>
        public static string RegisterDoneMsgBoxContent {
            get {
                return ResourceManager.GetString("RegisterDoneMsgBoxContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Register successful! 的本地化字符串。
        /// </summary>
        public static string RegisterDoneMsgBoxTitle {
            get {
                return ResourceManager.GetString("RegisterDoneMsgBoxTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Register failed. 的本地化字符串。
        /// </summary>
        public static string RegisterFailMsgBoxTitle {
            get {
                return ResourceManager.GetString("RegisterFailMsgBoxTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Confirm your register info 的本地化字符串。
        /// </summary>
        public static string RegisterWndTitle {
            get {
                return ResourceManager.GetString("RegisterWndTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Are you sure you want to delete this record? 的本地化字符串。
        /// </summary>
        public static string ReviewConfirmDelete {
            get {
                return ResourceManager.GetString("ReviewConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Data Type 的本地化字符串。
        /// </summary>
        public static string ReviewDataType {
            get {
                return ResourceManager.GetString("ReviewDataType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save 的本地化字符串。
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save Avg. Value 的本地化字符串。
        /// </summary>
        public static string SaveAvg {
            get {
                return ResourceManager.GetString("SaveAvg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Value saved 的本地化字符串。
        /// </summary>
        public static string Saved2DB {
            get {
                return ResourceManager.GetString("Saved2DB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Data List 的本地化字符串。
        /// </summary>
        public static string SaveDataTitle {
            get {
                return ResourceManager.GetString("SaveDataTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save Sel. Value 的本地化字符串。
        /// </summary>
        public static string SaveSel {
            get {
                return ResourceManager.GetString("SaveSel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Search 的本地化字符串。
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 New Port Defaults 的本地化字符串。
        /// </summary>
        public static string SettingDefaultCOM {
            get {
                return ResourceManager.GetString("SettingDefaultCOM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Language 的本地化字符串。
        /// </summary>
        public static string SettingLang {
            get {
                return ResourceManager.GetString("SettingLang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Language setting saved. But requires an application restart to fully take effect.
        ///Would you like to restart now? 的本地化字符串。
        /// </summary>
        public static string SettingLangSaved {
            get {
                return ResourceManager.GetString("SettingLangSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 COM 的本地化字符串。
        /// </summary>
        public static string SettingTitleCOM {
            get {
                return ResourceManager.GetString("SettingTitleCOM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 General 的本地化字符串。
        /// </summary>
        public static string SettingTitleGeneral {
            get {
                return ResourceManager.GetString("SettingTitleGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Image 的本地化字符串。
        /// </summary>
        public static string SettingTitleImg {
            get {
                return ResourceManager.GetString("SettingTitleImg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Measurement 的本地化字符串。
        /// </summary>
        public static string SettingTitleMeasurement {
            get {
                return ResourceManager.GetString("SettingTitleMeasurement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Proximity 的本地化字符串。
        /// </summary>
        public static string SettingTitleProx {
            get {
                return ResourceManager.GetString("SettingTitleProx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 An SQL exception has occurred. Your changes are not saved. The following information might help:
        ///
        ///%Exception
        ///
        ///To view the last valid value, search again to update this list. 的本地化字符串。
        /// </summary>
        public static string SQLReviewEx {
            get {
                return ResourceManager.GetString("SQLReviewEx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 User %User (%Type) has logged in. 的本地化字符串。
        /// </summary>
        public static string StatusLoggedIn {
            get {
                return ResourceManager.GetString("StatusLoggedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ready 的本地化字符串。
        /// </summary>
        public static string StatusReady {
            get {
                return ResourceManager.GetString("StatusReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Stop Bits 的本地化字符串。
        /// </summary>
        public static string StopBits {
            get {
                return ResourceManager.GetString("StopBits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Test Name 的本地化字符串。
        /// </summary>
        public static string TestName {
            get {
                return ResourceManager.GetString("TestName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unit of Measurement 的本地化字符串。
        /// </summary>
        public static string UoM {
            get {
                return ResourceManager.GetString("UoM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Write Timeout 的本地化字符串。
        /// </summary>
        public static string WriteT {
            get {
                return ResourceManager.GetString("WriteT", resourceCulture);
            }
        }
    }
}
