//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StdEqpTesting.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Loc {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Loc() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StdEqpTesting.Localization.Loc", typeof(Loc).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional Info.
        /// </summary>
        public static string AddInfo {
            get {
                return ResourceManager.GetString("AddInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add -&gt;.
        /// </summary>
        public static string AddRecvStr {
            get {
                return ResourceManager.GetString("AddRecvStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a Unit.
        /// </summary>
        public static string AddUnit {
            get {
                return ResourceManager.GetString("AddUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Addition Failed: Unit is empty or whitespace..
        /// </summary>
        public static string AddUnitFail_Empty {
            get {
                return ResourceManager.GetString("AddUnitFail_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Addition Failed: Unit already exists..
        /// </summary>
        public static string AddUnitFail_Existed {
            get {
                return ResourceManager.GetString("AddUnitFail_Existed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Addition Successful..
        /// </summary>
        public static string AddUnitSucc {
            get {
                return ResourceManager.GetString("AddUnitSucc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save current unit to a file for future use..
        /// </summary>
        public static string AddUnitTT {
            get {
                return ResourceManager.GetString("AddUnitTT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto add.
        /// </summary>
        public static string AutoAddRecvStr {
            get {
                return ResourceManager.GetString("AutoAddRecvStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When serial port is opened, automatically add the received string to data list if no more data is received in 1 second..
        /// </summary>
        public static string AutoAddRecvStrTT {
            get {
                return ResourceManager.GetString("AutoAddRecvStrTT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average Value.
        /// </summary>
        public static string Average {
            get {
                return ResourceManager.GetString("Average", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The average value of numbers in Data List..
        /// </summary>
        public static string AverageTT {
            get {
                return ResourceManager.GetString("AverageTT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Baud Rate.
        /// </summary>
        public static string BaudRate {
            get {
                return ResourceManager.GetString("BaudRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Camera List.
        /// </summary>
        public static string CameraList {
            get {
                return ResourceManager.GetString("CameraList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video Capabilities.
        /// </summary>
        public static string Capabilities {
            get {
                return ResourceManager.GetString("Capabilities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto clear.
        /// </summary>
        public static string ClearAfterAddingRecvStr {
            get {
                return ResourceManager.GetString("ClearAfterAddingRecvStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When auto add is on, auto clear is enforced..
        /// </summary>
        public static string ClearAfterAddingRecvStrDisabledTT {
            get {
                return ResourceManager.GetString("ClearAfterAddingRecvStrDisabledTT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear received string after it&apos;s been added to the data list..
        /// </summary>
        public static string ClearAfterAddingRecvStrTT {
            get {
                return ResourceManager.GetString("ClearAfterAddingRecvStrTT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close Port.
        /// </summary>
        public static string ClosePort {
            get {
                return ResourceManager.GetString("ClosePort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serial Port %Name closed.
        /// </summary>
        public static string COMClose {
            get {
                return ResourceManager.GetString("COMClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serial Port %Name opened.
        /// </summary>
        public static string COMOpen {
            get {
                return ResourceManager.GetString("COMOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings for %PortName has been saved.
        /// </summary>
        public static string COMSettingSaved {
            get {
                return ResourceManager.GetString("COMSettingSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Addition of Incomplete Record.
        /// </summary>
        public static string ConfirmAddEmptyRecord {
            get {
                return ResourceManager.GetString("ConfirmAddEmptyRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;re seeing this because Test Name or Unit is left empty or are of whitespaces.
        ///
        ///Press No to go back so you can make some changes, otherwise you can press Yes to add this incomplete record, which can cause confusion..
        /// </summary>
        public static string ConfirmAddEmptyRecordDesc {
            get {
                return ResourceManager.GetString("ConfirmAddEmptyRecordDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Bits.
        /// </summary>
        public static string DataBits {
            get {
                return ResourceManager.GetString("DataBits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connecting to database.....
        /// </summary>
        public static string DBConnect {
            get {
                return ResourceManager.GetString("DBConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encoding.
        /// </summary>
        public static string Encoding {
            get {
                return ResourceManager.GetString("Encoding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can press F5 to refresh this..
        /// </summary>
        public static string F5Refresh {
            get {
                return ResourceManager.GetString("F5Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Name.
        /// </summary>
        public static string FileName {
            get {
                return ResourceManager.GetString("FileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %Num COM device(s) detected.
        /// </summary>
        public static string FoundCOMDevices {
            get {
                return ResourceManager.GetString("FoundCOMDevices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %Num video device(s) detected.
        /// </summary>
        public static string FoundVideoDevices {
            get {
                return ResourceManager.GetString("FoundVideoDevices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Handshake.
        /// </summary>
        public static string Handshake {
            get {
                return ResourceManager.GetString("Handshake", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image Saved.
        /// </summary>
        public static string ImageSaved {
            get {
                return ResourceManager.GetString("ImageSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file name without extension.
        ///Click to use the current system time..
        /// </summary>
        public static string ImgNameTT {
            get {
                return ResourceManager.GetString("ImgNameTT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JPEG Quality.
        /// </summary>
        public static string JPEGQuality {
            get {
                return ResourceManager.GetString("JPEGQuality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string LoginButton {
            get {
                return ResourceManager.GetString("LoginButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your credentials below..
        /// </summary>
        public static string LoginEnterCred {
            get {
                return ResourceManager.GetString("LoginEnterCred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong username or password..
        /// </summary>
        public static string LoginFailedStatus {
            get {
                return ResourceManager.GetString("LoginFailedStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password:.
        /// </summary>
        public static string LoginPassword {
            get {
                return ResourceManager.GetString("LoginPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password only contains ASCII characters.
        ///And should have at least 4 characters..
        /// </summary>
        public static string LoginPWErrorTT {
            get {
                return ResourceManager.GetString("LoginPWErrorTT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username only contains letters, numbers and underscores.
        ///And have no more than 20 characters..
        /// </summary>
        public static string LoginUNErrorTT {
            get {
                return ResourceManager.GetString("LoginUNErrorTT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username:.
        /// </summary>
        public static string LoginUsername {
            get {
                return ResourceManager.GetString("LoginUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome!.
        /// </summary>
        public static string LoginWelcome {
            get {
                return ResourceManager.GetString("LoginWelcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string LoginWndTitle {
            get {
                return ResourceManager.GetString("LoginWndTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading.
        /// </summary>
        public static string MainWndTitle {
            get {
                return ResourceManager.GetString("MainWndTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        public static string NavExport {
            get {
                return ResourceManager.GetString("NavExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image Device.
        /// </summary>
        public static string NavImg {
            get {
                return ResourceManager.GetString("NavImg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Displacement.
        /// </summary>
        public static string NavProx {
            get {
                return ResourceManager.GetString("NavProx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Review.
        /// </summary>
        public static string NavReview {
            get {
                return ResourceManager.GetString("NavReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string NavSettings {
            get {
                return ResourceManager.GetString("NavSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Measure (COM).
        /// </summary>
        public static string NavTest {
            get {
                return ResourceManager.GetString("NavTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No COM port detected.
        /// </summary>
        public static string NoCOMTabHeader {
            get {
                return ResourceManager.GetString("NoCOMTabHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please check your settings and press F5 to refresh..
        /// </summary>
        public static string NoCOMTabInstruction {
            get {
                return ResourceManager.GetString("NoCOMTabInstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value is not saved.
        /// </summary>
        public static string NotSaved2DB {
            get {
                return ResourceManager.GetString("NotSaved2DB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open File Location.
        /// </summary>
        public static string OpenFileLoc {
            get {
                return ResourceManager.GetString("OpenFileLoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Port.
        /// </summary>
        public static string OpenPort {
            get {
                return ResourceManager.GetString("OpenPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parity.
        /// </summary>
        public static string Parity {
            get {
                return ResourceManager.GetString("Parity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PLC.
        /// </summary>
        public static string PLC {
            get {
                return ResourceManager.GetString("PLC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ILS file loaded from %Path.
        /// </summary>
        public static string PLCLoadedILS {
            get {
                return ResourceManager.GetString("PLCLoadedILS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ILS file is not loaded..
        /// </summary>
        public static string PLCNotLoadILS {
            get {
                return ResourceManager.GetString("PLCNotLoadILS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open ILS File.
        /// </summary>
        public static string PLCOpenILS {
            get {
                return ResourceManager.GetString("PLCOpenILS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port Properties.
        /// </summary>
        public static string PortProp {
            get {
                return ResourceManager.GetString("PortProp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ^^^^Properties^^^^.
        /// </summary>
        public static string PortPropExpander {
            get {
                return ResourceManager.GetString("PortPropExpander", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read Timeout.
        /// </summary>
        public static string ReadT {
            get {
                return ResourceManager.GetString("ReadT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recv. String.
        /// </summary>
        public static string RecvStr {
            get {
                return ResourceManager.GetString("RecvStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🔄 Refresh.
        /// </summary>
        public static string RefreshBtn {
            get {
                return ResourceManager.GetString("RefreshBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string RegisterButton {
            get {
                return ResourceManager.GetString("RegisterButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm your password below:.
        /// </summary>
        public static string RegisterConfirmPass {
            get {
                return ResourceManager.GetString("RegisterConfirmPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;ll be registered as:.
        /// </summary>
        public static string RegisterConfirmUser {
            get {
                return ResourceManager.GetString("RegisterConfirmUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please always remember your username and password..
        /// </summary>
        public static string RegisterDoneMsgBoxContent {
            get {
                return ResourceManager.GetString("RegisterDoneMsgBoxContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register successful!.
        /// </summary>
        public static string RegisterDoneMsgBoxTitle {
            get {
                return ResourceManager.GetString("RegisterDoneMsgBoxTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register failed..
        /// </summary>
        public static string RegisterFailMsgBoxTitle {
            get {
                return ResourceManager.GetString("RegisterFailMsgBoxTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm your register info.
        /// </summary>
        public static string RegisterWndTitle {
            get {
                return ResourceManager.GetString("RegisterWndTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this record?.
        /// </summary>
        public static string ReviewConfirmDelete {
            get {
                return ResourceManager.GetString("ReviewConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Type.
        /// </summary>
        public static string ReviewDataType {
            get {
                return ResourceManager.GetString("ReviewDataType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Avg. Value.
        /// </summary>
        public static string SaveAvg {
            get {
                return ResourceManager.GetString("SaveAvg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value saved.
        /// </summary>
        public static string Saved2DB {
            get {
                return ResourceManager.GetString("Saved2DB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data List.
        /// </summary>
        public static string SaveDataTitle {
            get {
                return ResourceManager.GetString("SaveDataTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Image.
        /// </summary>
        public static string SaveImg {
            get {
                return ResourceManager.GetString("SaveImg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to save image.
        /// </summary>
        public static string SaveImgFailed {
            get {
                return ResourceManager.GetString("SaveImgFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Sel. Value.
        /// </summary>
        public static string SaveSel {
            get {
                return ResourceManager.GetString("SaveSel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Port Defaults.
        /// </summary>
        public static string SettingDefaultCOM {
            get {
                return ResourceManager.GetString("SettingDefaultCOM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string SettingLang {
            get {
                return ResourceManager.GetString("SettingLang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language setting saved. But requires an application restart to fully take effect.
        ///Would you like to restart now?.
        /// </summary>
        public static string SettingLangSaved {
            get {
                return ResourceManager.GetString("SettingLangSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image Save Directory (Relative).
        /// </summary>
        public static string SettingsImgDir {
            get {
                return ResourceManager.GetString("SettingsImgDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The directory here is relative. For example, entering &quot;SavedImage&quot; will save the image to the &quot;SavedImage&quot; folder in the root folder of the application.
        ///Leaving this field empty will make the image to be saved in the root folder of the app..
        /// </summary>
        public static string SettingsImgDirTT {
            get {
                return ResourceManager.GetString("SettingsImgDirTT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No settings are available yet.....
        /// </summary>
        public static string SettingsNotAvail {
            get {
                return ResourceManager.GetString("SettingsNotAvail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COM.
        /// </summary>
        public static string SettingTitleCOM {
            get {
                return ResourceManager.GetString("SettingTitleCOM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DISP..
        /// </summary>
        public static string SettingTitleDisplacement {
            get {
                return ResourceManager.GetString("SettingTitleDisplacement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string SettingTitleGeneral {
            get {
                return ResourceManager.GetString("SettingTitleGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image.
        /// </summary>
        public static string SettingTitleImg {
            get {
                return ResourceManager.GetString("SettingTitleImg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Measurement.
        /// </summary>
        public static string SettingTitleMeasurement {
            get {
                return ResourceManager.GetString("SettingTitleMeasurement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An SQL exception has occurred. Your changes are not saved. The following information might help:
        ///
        ///%Exception
        ///
        ///To view the last valid value, search again to update this list..
        /// </summary>
        public static string SQLReviewEx {
            get {
                return ResourceManager.GetString("SQLReviewEx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        public static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User %User (%Type) has logged in..
        /// </summary>
        public static string StatusLoggedIn {
            get {
                return ResourceManager.GetString("StatusLoggedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready.
        /// </summary>
        public static string StatusReady {
            get {
                return ResourceManager.GetString("StatusReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        public static string Stop {
            get {
                return ResourceManager.GetString("Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop Bits.
        /// </summary>
        public static string StopBits {
            get {
                return ResourceManager.GetString("StopBits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test Name.
        /// </summary>
        public static string TestName {
            get {
                return ResourceManager.GetString("TestName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit of Measurement.
        /// </summary>
        public static string UoM {
            get {
                return ResourceManager.GetString("UoM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write Timeout.
        /// </summary>
        public static string WriteT {
            get {
                return ResourceManager.GetString("WriteT", resourceCulture);
            }
        }
    }
}
